version: "2"
run:
  issues-exit-code: 1
  tests: true
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
linters:
  default: none
  enable:
    - bodyclose
    - dogsled
    - errcheck
    - gocognit
    - goconst
    - gocritic
    - gosec
    - govet
    - ineffassign
    - nakedret
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    dogsled:
      max-blank-identifiers: 2
    dupl:
      threshold: 150
    errcheck:
      check-type-assertions: false
      check-blank: false
    funlen:
      lines: 60
      statements: 40
    gocognit:
      min-complexity: 30
    goconst:
      min-len: 3
      min-occurrences: 3
    gocritic:
      disabled-checks:
        - captLocal
        - ifElseChain
      enabled-tags:
        - diagnostic
        - style
        - performance
    gocyclo:
      min-complexity: 30
    godox:
      keywords:
        - TODO
        - BUG
        - FIXME
        - NOTE
        - OPTIMIZE
        - HACK
    gosec:
      excludes:
        - G104
        - G107
        - G115
        - G304
    govet:
      settings:
        printf:
          funcs:
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
    lll:
      line-length: 120
      tab-width: 1
    nakedret:
      max-func-lines: 30
    prealloc:
      simple: true
      range-loops: true
      for-loops: false
    staticcheck:
      checks:
        - all
        - -ST1000
        - -ST1003
        - -ST1005
        - -ST1016
        - -ST1020
        - -ST1021
        - -ST1022
      initialisms:
        - ACL
        - API
        - ASCII
        - CPU
        - CSS
        - DNS
        - EOF
        - GUID
        - HTML
        - HTTP
        - HTTPS
        - ID
        - IP
        - JSON
        - QPS
        - RAM
        - RPC
        - SLA
        - SMTP
        - SQL
        - SSH
        - TCP
        - TLS
        - TTL
        - UDP
        - UI
        - GID
        - UID
        - UUID
        - URI
        - URL
        - UTF8
        - VM
        - XML
        - XMPP
        - XSRF
        - XSS
        - SIP
        - RTP
        - AMQP
        - DB
        - TS
      dot-import-whitelist:
        - fmt
      http-status-code-whitelist:
        - "200"
        - "400"
        - "404"
        - "500"
    unparam:
      check-exported: false
    whitespace:
      multi-if: false
      multi-func: false
    wsl:
      strict-append: false
      allow-assign-and-call: true
      allow-multiline-assign: true
      force-case-trailing-whitespace: 0
      allow-trailing-comment: false
      allow-cuddle-declarations: false
  exclusions:
    generated: lax
    rules:
      - linters:
          - dupl
          - errcheck
          - funlen
          - gocyclo
          - gosec
        path: _test\.go
      - linters:
          - lll
        source: '^//go:generate '
    paths:
      - pkg/sqlc
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
  exclusions:
    generated: lax
    paths:
      - pkg/sqlc
      - third_party$
      - builtin$
      - examples$
