services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: gobp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - gobp_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  gobp_data:
