[server]
port = 3000

[app]
name = "MyApp"
dsn = ""
host = "http://localhost:3000"

[mail]
provider="browser"

[auth.sko]
url = "http://localhost:3004"
client_secret = ""

[auth.msentra]
client_id=""
client_secret=""
callbackURL="http://localhost:3000/auth/callback/microsoftonline"
