[server]
port = 3001

[app]
name = "MyApp"
dsn = ""
host = "http://localhost:3000"

[redis]
url = "redis://default@redis:6379"

[mails]
provider="browser"
linker="gnu"

[auth.sko]
url = "http://host.docker.internal:3004"
client_secret = ""

[auth.msentra]
client_id=""
client_secret=""
callback_url="http://localhost:8000/api/auth/callback/azureadv2"
tenant_id=""
