[server]
host = "0.0.0.0"
port = 8000

[app]
name = "MyApp"
dsn = ""
host = "https://am.studentkickoff.be"

[mails]
provider="smtp"
linker="musl"

[mails.smtp]
address='smtp.eu.mailgun.org'
port=587
domain='studentkickoff.be'
username=""
password=""

[auth.sko]
url = "http://localhost:3004"
client_secret = ""

[auth.msentra]
client_id=""
client_secret=""
redirect_url=""
tenant_id=""
